spring:
  application:
    name: security
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    druid:
      filters: slf4j
      filter:
        slf4j:
          enabled: true
      aop-patterns: com.yibo.security.dao.*
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yibo.security.entity
logging:
  level:
    com.yibo.security.dao: debug